### ISSUE TITLE
about the dalle2 editting

### ISSUE THREAD

**Issue by Bailey-24** [ffm5113/python_dalle2_image_edit#1]
Hi, thanks for you grate job.
I have a questions about the dalle2 model.
what does the input mask looks like?
Does the black region can't adjust, the white can adjust?
![mask2](https://github.com/ffm5113/python_dalle2_image_edit/assets/72083251/289a6b45-8050-4ff0-b8a0-751c548961fd)

how can i get what i want picture?
the input image is pure gray.
and the mask show as above.
my prompt is "a keyboard in the center, a cup in the left of keyboard, an ipad on top of keyboard, a mouse in the right of keyboard".
but i got this. does it mean the white region in the mask picture can't adjust?
![image](https://github.com/ffm5113/python_dalle2_image_edit/assets/72083251/1def5943-47a4-4c7f-8244-40380909d737)

**Comment by heyfoz** [comment]
Hello @Bailey-24,

Apologies for the delay. I just noticed your question. 

The input mask for DALL·E 2 should be a PNG image where:

- Transparent regions: These areas indicate where the image should be edited based on your prompt.
- Opaque regions: These areas will remain unchanged and cannot be adjusted.
- Explanation with Your Provided Images

Based on the images you provided in your question:

Mask Image:

In this mask image, the transparent areas indicate the parts of the original image that DALL·E 2 should modify. The opaque (white) areas will remain unchanged. But if your image was not PNG and had black on the background area, that may be the issue.

Generated Image:

Your prompt was: "a keyboard in the center, a cup to the left of the keyboard, an iPad on top of the keyboard, a mouse to the right of the keyboard".

Interpretation
Given the generated image:

Transparent Region Adjustments: 
The transparent regions in the mask image are where DALL·E 2 has applied modifications based on your prompt. Since there didn't appear to be any transparent regions in the mask, I think it just generated a regular image. 

Opaque Region: 
The opaque regions have remained unchanged, as expected.

To get the image you want:

Ensure Correct Masking: Make sure the transparent areas in the mask are precisely where you want the new elements to be placed. In your case, the transparent regions should cover the areas where you want the keyboard, cup, iPad, and mouse.
Adjust the Prompt if Necessary: Sometimes, tweaking the prompt can help get more accurate results. You can try providing more detailed descriptions or slightly adjusting the positions described in the prompt.

Additional Information
You can also check out DALL·E on [labs.openai.com](https://labs.openai.com/). 
As per the site, "DALL·E 3 has higher quality images, improved prompt adherence, and we've started rolling out image editing. It is available for ChatGPT Plus, Team and Enterprise, and the OpenAI API." Note that DALL·E 2 still works for the API.

Useful Resources
[OpenAI Edit Image API Reference](https://platform.openai.com/docs/api-reference/images/createEdit)
[OpenAI Edit Image Docs](https://platform.openai.com/docs/guides/images/edits-dall-e-2-only)
[DALL·E](https://labs.openai.com/)

Happy coding!
